### ISSUE TITLE
Traefik virtualhost subfolder (router PathPrefix + middleware StripPrefix)

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#110]
In some case we want to create a virtulahost that reverses a container from a subfolder, ie https://myapp.test/app

https://medium.com/@iced_burn/reverse-proxy-in-traefik-with-subdirectories-eef4261939e

There should be an easy way to do this inside ddb, and it should be available on services and external services.

**Comment by Toilal** [comment]
Here's the current custom template I wrote for an extra_service requiring the /diffusion path

```yaml
docker:
  disabled_services: ['python', 'gunicorn', 'apache']
traefik:
  extra_services:
    django-dev:
      domain: "{{core.domain.sub}}.{{core.domain.ext}}"
      url: "http://{{docker.debug.host}}:8000"
  extra_services_config_template: |+
    # This configuration file has been automatically generated by ddb
    [http.routers]
    {%- if _local.https is none or _local.https is sameas false %}
      [http.routers.extra-service-{{_local.id}}]
        rule = "{{_local.rule}}"{% if not _local.redirect_to_https %} && "PathPrefix(`/diffusion{regex:$$|/.*}`)"{% endif %}
        entrypoints = ["http"]
        service = "extra-service-{{_local.id}}"
    {%- if _local.redirect_to_https %}
        middlewares = ["extra-service-{{_local.id}}-redirect-to-https"]
    {%- else %}
        middlewares = ["extra-service-{{_local.id}}-stripprefix"]
    {%- endif %}
    {%- endif %}
    {%- if _local.https is none or _local.https is sameas true %}
      [http.routers.extra-service-{{_local.id}}-tls]
        rule = "{{_local.rule}} && PathPrefix(`/diffusion{regex:$$|/.*}`)"
        entrypoints = ["https"]
        tls = true
        service = "extra-service-{{_local.id}}"
        middlewares = ["extra-service-{{_local.id}}-stripprefix"]
    {%- if _local.certresolver is defined %}
        [http.routers.extra-service-{{_local.service}}-tls.tls]
          certResolver = "{{_local.certresolver}}"
    {%- endif %}
    {%- endif %}

    [http.middlewares]
    {%- if _local.redirect_to_https %}
      [http.middlewares.extra-service-{{_local.id}}-redirect-to-https.redirectScheme]
        scheme = "https"
    {%- endif %}
      [http.middlewares.extra-service-{{_local.id}}-stripprefix.stripPrefix]
        prefixes = "/diffusion"

    [http.services]
      [http.services.extra-service-{{_local.id}}]
        [http.services.extra-service-{{_local.id}}.loadBalancer]
          [[http.services.extra-service-{{_local.id}}.loadBalancer.servers]]
            url = "{{_local.url}}"

```

It generates the following configuration which works as expected.

```toml                                    
# This configuration file has been automatically generated by ddb
[http.routers]
  [http.routers.extra-service-django-dev]
    rule = "Host(`inserjeunes.test`)"
    entrypoints = ["http"]
    service = "extra-service-django-dev"
    middlewares = ["extra-service-django-dev-redirect-to-https"]
  [http.routers.extra-service-django-dev-tls]
    rule = "Host(`inserjeunes.test`) && PathPrefix(`/diffusion{regex:$$|/.*}`)"
    entrypoints = ["https"]
    tls = true
    service = "extra-service-django-dev"
    middlewares = ["extra-service-django-dev-stripprefix"]

[http.middlewares]
  [http.middlewares.extra-service-django-dev-redirect-to-https.redirectScheme]
    scheme = "https"
  [http.middlewares.extra-service-django-dev-stripprefix.stripPrefix]
    prefixes = "/diffusion"

[http.services]
  [http.services.extra-service-django-dev]
    [http.services.extra-service-django-dev.loadBalancer]
      [[http.services.extra-service-django-dev.loadBalancer.servers]]
        url = "http://172.17.0.1:8000"

```
