### ISSUE TITLE
Exclude some properties from bash activation

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#120]
It doesn't make sense to export some of the properties as environment variables, and it may cause errors because of special characters.

```yaml
permissions:
  specs:
    "bin/dependency-check": "+x"
    "bin/sonar-scanner": "+x"
```

cause the following errors on activation

```
bash: export: « DDB_PERMISSIONS_SPECS_BIN/DEPENDENCY_CHECK=+x » : identifiant non valable
bash: export: « DDB_PERMISSIONS_SPECS_BIN/SONAR_SCANNER=+x » : identifiant non valable
```
