### ISSUE TITLE
Issues when trying to merge some values in default configuration

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#121]
I want to append `dev-services` to list of available environments, so this configuration should work.

**ddb.yml**
```
core:
  env:
    available:
      merge: append_if_missing
      value: dev-services
```

But effective configuration is not as expected

```
$ ddb config --variables | grep core.env.available
core.env.available: ['merge', 'value']
```

It should be

```
$ ddb config --variables | grep core.env.available
core.env.available: ['prod', 'stage', 'ci', 'dev', 'dev-services']
```
