### ISSUE TITLE
Add more configuration files from a list of defined filename in main configuration

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#123]
**ddb.yml**
```yml
core: 
  configuration: 
    extra_filenames: ['ddb.custom']
```

This should also load configuration from 'ddb.custom.yml' in all supported paths (project, home, ddb_home).
