### ISSUE TITLE
ddb activate error with permissions specs containing slash

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#160]
With such configuration

```yaml
permissions:
  specs:
    "bin/dependency-check": "+x"
    "bin/sonar-scanner": "+x"
```

ddb activation still raise some errors in bash.

```
bash: export: « DDB_PERMISSIONS_SPECS_BIN-DEPENDENCY_CHECK=+x » : identifiant non valable
bash: export: « DDB_PERMISSIONS_SPECS_BIN-SONAR_SCANNER=+x » : identifiant non valable
```

This is caused by the `-` dash.
