### ISSUE TITLE
self.path.directories should resolve relative directories

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#168]
I try to add some entries in shelf.path.directories to add more project folder in the path, but it doesn't work well because relative paths are not handled properly.

```
shell:
  path:
    directories:
      value: ["./main/src/main/webapp/node", "./main/src/main/webapp/node_modules/.bin"]
      merge: "append"
```

ddb config

```
shell:
  path:
      directories:
      - /home/toilal/projects/OFB-ESTAMP/main/.bin
      - /home/toilal/projects/OFB-ESTAMP/main/bin
      - /home/toilal/.docker-devbox/.bin
      - /home/toilal/.docker-devbox/ddb/.bin
      - ./main/src/main/webapp/node
      - ./main/src/main/webapp/node_modules/.bin
```

Relative configuration paths should be resolved as absolute paths using project directory as current working directory.
