### ISSUE TITLE
Feature Jinja : add custom variables to be used in template

### ISSUE THREAD

**Issue by darkanakin41** [gfi-centre-ouest/docker-devbox-ddb#40]
For instance, if you want to propagate the user and password for sql database, you would have : 
```yaml
jinja:
  extVars:
    db_user: toto
    db_password: toto
```
Which would be used in jinja template as {{ jinja.extVars.db_user }}
