### ISSUE TITLE
copy doesn't works well when cache is already populated

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#77]
When cache is already populated, adding this configuration has no effect.

```
copy:
  specs:
    - source: /usr/local/share/ca-certificates/GFI_Informatique_*
      destination: .ca-certificates
      dispatch:
        - ".docker/*"
```

Current workaround is to run ddb configure with `--clear-cache` flag.
