### ISSUE TITLE
copy doesn't add generated files to .gitignore

### ISSUE THREAD

**Issue by Toilal** [gfi-centre-ouest/docker-devbox-ddb#78]
Copied files are not added to `.gitignore`

```
copy:
  specs:
    - source: /usr/local/share/ca-certificates/GFI_Informatique_*
      destination: .ca-certificates
      dispatch:
        - ".docker/*"
```
